spring:
  application:
    name: Configuration Service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BaiBeiCha/config-repo.git
          clone-on-start: true

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka