spring:
  application:
    name: UserManagementService

  datasource:
    url: jdbc:postgresql://users-db:5431/users
    username: users
    password: users
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka