spring:
  application:
    name: UserManagementService

  datasource:
    url: jdbc:postgresql://users-db:5432/users
    username: users
    password: users
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
